server {
    listen 80;
    server_name tnut.minhlatao1.id.vn;

    location / {
        root /var/www/html/site1;
        index index.html;
    }

    # Định tuyến API sang Node-RED
    location /api/ {
        proxy_pass http://nodered_app:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name tnut.minhlatao2.id.vn;

    location / {
        root /var/www/html/site2;
        index index.html;
    }
}